# .github/dependabot.yml
version: 2
updates:
  # Root package.json
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      dev-dependencies:
        dependency-type: 'development'

  # Your ax-llm/ax package in src directory
  - package-ecosystem: 'npm'
    directory: '/src/ax' # Adjusted to match your src/* workspace pattern
    schedule:
      interval: 'weekly'
      day: 'monday'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      dev-dependencies:
        dependency-type: 'development'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      prefix: 'ci'
      include: 'scope'
